### ISSUE TITLE
Error on product pages

### ISSUE THREAD

**Issue by dramatisrod** [rhyswynne/easy-digital-downloads-taxamo-integration#10]
Just installed and error appears at top of each product page

Warning: Invalid argument supplied for foreach() in /home/dramati3/public_html/wp-content/plugins/easy-digital-downloads-taxamo-integration/taxamo-edd-integration.php on line 738

![taxamoerror](https://cloud.githubusercontent.com/assets/10449221/5662438/ec7e1126-9730-11e4-89ba-15d8b10d23e0.jpg)

**Comment by rhyswynne** [comment]
Hi @dramatisrod,

I think I know what the issue will be, and put a check which should fix the error you are having.

Download this - https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/archive/master.zip - it could fix the error you are having. It's 1.0.2. You'll have to install it via FTP.

If you confirm it's working I'll push it out to WordPress.org.

Thanks!

**Comment by dramatisrod** [comment]
Hi Rhys,

Thanks, that has removed the error and my pages display without issue.

Rod

**Comment by rhyswynne** [comment]
Great. Closing this ticket.
