### ISSUE TITLE
Design Placement on EDD VAT Number Box

### ISSUE THREAD

**Issue by rhyswynne** [rhyswynne/easy-digital-downloads-taxamo-integration#11]
When you ask for a VAT Number, the VAT Number box is located in the "Personal Info" section of the site, from Taxamo QA testing, somebody couldn't find it, despite being activated.

I think it should be in the Billing Section, if anything....maybe?

**Comment by samikeijonen** [comment]
I think we should at least test it in Billing section.

Also I noticed that VAT number checkbox and text field appears in two places now. When I have enabled that users can create account in my site VAT number checkbox appears second time after username and password fields when logged out.

I think one time is enough:)

**Comment by samikeijonen** [comment]
`edd_purchase_form_user_info` hook probably isn't the best place because it's fired two times like I mentioned above.

I'll vote for `edd_cc_billing_top` hook.

**Comment by rhyswynne** [comment]
I've decided to make an executive decision and move it to the bottom. Feel it kind of feels better from staring at WooCommerce's checkout process all day. So switched it to `edd_cc_billing_bottom`.

Works though.
