### ISSUE TITLE
How does this handle prices inclusive of VAT?

### ISSUE THREAD

**Issue by dramatisrod** [rhyswynne/easy-digital-downloads-taxamo-integration#12]
If I leave the EDD Tax tab as shown in your documentation - enter prices inclusive of tax, display prices on checkout page exclusive of tax - the checkout page adds tax to the supposedly already inclusive price anyway. In fact the I'm not sure either of the selectors has any effect, so how can a seller enter one single price inclusive of whatever tax is levied? Taxamo allows for it with its "Force universal pricing" which I selected - but does the plugin?

**Comment by rhyswynne** [comment]
Good question. It isn't yet implemented this but wasn't aware the "Force Universal Pricing" feature of Taxamo. I will try and implement something over the next few days or weeks.

**Comment by samikeijonen** [comment]
Vatinfoeu plugin is using filter `edd_tax_rate`, not `edd_get_cart_tax`. 

https://github.com/radishconcepts/edd-vatinfoeu/blob/master/includes/core/class-tax.php#L10

`edd_tax_rate` seems to play nicely also with discount code issue #13. Is it possible to use this filter instead in this plugin?

**Comment by samikeijonen** [comment]
This is mostly reminder of myself. Tax rate from the API can be called similar like tax amount like this `$resp->transaction->transaction_lines[0]->tax_rate`.

I can play around with `edd_tax_rate` filter.

**Comment by rhyswynne** [comment]
Right I had some time this weekend and prepared this.

Basically, it will allow you to set the CART (not individual products) inclusive of tax. So if you put your products as €10, and there is a 20% VAT rate, the price of the product will be set as €8.33.

Been a bit of a rewrite, so will appreciate testing on this. Got this running on https://winwar.co.uk, and it appears to be working fine. However would appreciate some second looks before releasing.

Some test data is here - https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/wiki/Testing-Data if you wish to use it.

**Comment by rhyswynne** [comment]
Closing it as it appears to be working fine.
