### ISSUE TITLE
Discount codes

### ISSUE THREAD

**Issue by samikeijonen** [rhyswynne/easy-digital-downloads-taxamo-integration#13]
I was testing the plugin with 100% discount. Without the plugin I can get the product 0 dollars. But if I activate this plugin I still need to pay taxes. 

For example product price is set to 30$. I set 100% discount and I still need to pay 7,2$ taxes here in Finland (24% VAT).

I wonder is the tax calculated in wrong order in core plugin or in this plugin? Or is this just how it suppose to be.

**Comment by rhyswynne** [comment]
Hi @samikeijonen,

Thanks for this, I've taken a look at it tonight.

From #12, I tried using `edd_tax_rate`, but unfortunately I kept getting out of memory errors. However I've an update that I'm pushing live which I've tested and it does appear to fix this issue. Could you give it a test and if it works then I'll push it live :).

Thanks!

**Comment by samikeijonen** [comment]
I'll test tomorrow or friday. Also vatinfoeu pushed a lot of new stuff in their API and in the Plugin. There is pretty cool things happening and we can pick something from there.

https://github.com/radishconcepts/edd-vatinfoeu-dev/tree/1.0.0

**Comment by rhyswynne** [comment]
Hi @samikeijonen,

Starred it, will take a look.

Obviously we're kind of limited by Taxamo's API, but I've a call with them today at some point, so if there's anything specifically you want in there, then I'll pass it onto them.

**Comment by samikeijonen** [comment]
We'll need easy way to get tax rate from Taxamo. That way we could test `edd_tax_rate` filter and see if it's better in this plugin also.

**Comment by rhyswynne** [comment]
Closing this as I think I fixed it.
