### ISSUE TITLE
UK VAT Law Implementation

### ISSUE THREAD

**Issue by rhyswynne** [rhyswynne/easy-digital-downloads-taxamo-integration#17]
So one of the things I found out was that Taxamo has implementations so that UK registered businesses that don't go over the UK VAT Threshold (around £80,000 turnover) don't have to declare VAT or add VAT onto their orders.

It's something I would like to add at some point. Particularly as it affects me haha :D

**Comment by NateWr** [comment]
@rhyswynne this already works. Taxamo takes care of everything if you check this box.

![taxamo-no-domestic-vat](https://cloud.githubusercontent.com/assets/2306629/5992025/0ddad67c-aa0c-11e4-92eb-81acd604b123.png)

Then try checking out yourself (from UK IP) and you'll see no tax is added. To be legally compliant, you needed to register for VAT under the special exemption category, "Supplies of digital services" [source](https://www.gov.uk/register-and-use-the-vat-mini-one-stop-shop#businesses-currently-below-the-uk-vat-registration-threshold).

**Comment by rhyswynne** [comment]
So it does. Closing this! :)
