### ISSUE TITLE
Asked to Confirm Billing Details on $0 Purchase

### ISSUE THREAD

**Issue by nosegraze** [rhyswynne/easy-digital-downloads-taxamo-integration#20]
If your cart total is $0 (meaning you're downloading free items), the billing address form doesn't show up (which makes sense). But when you try to submit the order, you get this error message:

Error: Please confirm that the billing address is correct.

But the box to confirm that doesn't show up because the whole billing section isn't there.

So presumably that checkbox should only be validated if the billing fields are actually being shown.

**Comment by rhyswynne** [comment]
Hi!

Yeah this bug was caught by @ericnicolaas. I've merged his changes into the github as they work for me, could you test out the latest trunk (should be 1.2-beta) and see if this fixes the issue you are having?

Thanks :)

Rhys

**Comment by nosegraze** [comment]
Thanks very much! :) I got the update and believe it's working fine now.

**Comment by jakemcmurchie** [comment]
Hi. 
I'm using version 1.4 and having this problem. Is this a recurrence of the bug?
Thanks.

**Comment by jakemcmurchie** [comment]
Upon further investigation I noticed the check_self_declaration() function calls edd_get_cart_subtotal() to ascertain whether or not to validate against the country field, which calculates the total *before* discounts. Changing this to edd_get_cart_total() seems to fix the problem. Should this be logged as a bug?

**Comment by rhyswynne** [comment]
Please do :). I need to look at what has happened and what's changed.
