### ISSUE TITLE
Warning on Refund

### ISSUE THREAD

**Issue by rhyswynne** [rhyswynne/easy-digital-downloads-taxamo-integration#24]
@NateWr reported this on #1 :-

I just tried to process a refund and got a PHP Warning:

```
Warning: Invalid argument supplied for foreach() in /home/themes/public_html/wp-content/plugins/taxamo-edd-integration/taxamo-edd-integration.php on line 776
```

Note that my copy is slightly out of date with master. It's pointing at what is now [line 786](https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/master/taxamo-edd-integration.php#L786).

```
foreach ( $taxamo_transaction_lines as $taxamo_transaction_line ) {
```

This refund was for a payment without any Taxamo transaction info, so probably need to check the transactions that taxamo is returning there. I'm into something else at the moment so can't look into this right away.

Sticking it on it's own ticket as it'll remind me to take a look at it :)

**Comment by rhyswynne** [comment]
Hi @NateWr,

Quick question regarding this, was this refunded on an order that was made before Taxamo was implemented?

I created an extra field in the payment_meta which is 'taxamo_transaction_lines', which would suggest that with your error it isn't there.

I think.....

**Comment by rhyswynne** [comment]
I'm unable to replicate this on a test enviroment, so am just guessing.

**Comment by NateWr** [comment]
Yeah, this was a purchase made before Taxamo was implemented, so wouldn't have any data associated with it. Maybe you can replicate just by deactivating the plugin and making a purchase?

**Comment by rhyswynne** [comment]
Replicated - take a look at https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/commit/345aa9d95734d4fda97d0d76824ebec326a3c3b3, that should fix this issue.

**Comment by rhyswynne** [comment]
Happy this is fine now. Closing it
