### ISSUE TITLE
Tax Rates is Not Applied Correctly for Country Outside The EU

### ISSUE THREAD

**Issue by maurisrx** [rhyswynne/easy-digital-downloads-taxamo-integration#28]
When I set tax rates manually for country outside the EU on Downloads > Settings > Taxes, the tax is added to the original price on checkout page, not as tax. The total price is also not changed.

See the images below:

The tax rate is set to 10%.
http://screencast.com/t/vW7BJKi8J

The tax is added to original price, not as tax. 
http://screencast.com/t/beYIqyBxpHD

**Comment by rhyswynne** [comment]
Hi @maurisrx,

Thanks for your bug, and your thorough analysis at it.

I've taken a look at it and I think I've got it, in that it's working locally. It is quite difficult to test outside the UK, but it reverts to a default tax rate should the tax rate be zero and the country be outside the EU. Please could you test the latest commit https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/commit/58d0c68effa9353d94cbc6b25a4f9d12d11eecc5 (as a 1.4-beta) and let me know? 

Cheers, and sorry for the delay in getting back to you :)

Rhys

**Comment by maurisrx** [comment]
Hi Rhys,

The 1.4-beta seems has fixed the bug. I've tested it in my localhost. After choosing the country on checkout, the total price and tax are updated correctly.

Mauris

**Comment by rhyswynne** [comment]
Superb. Closing this :)
