### ISSUE TITLE
PayPal's IP being passed to Taxamo

### ISSUE THREAD

**Issue by nosegraze** [rhyswynne/easy-digital-downloads-taxamo-integration#29]
I started noticing that every single purchase that had VAT being applied had conflicting evidence. The IP never matched the country the customer selected. Then I realized that every single transaction had the same IP address ( 173.0.81.1 ), which is PayPal's IP (that's the checkout method I use). But if I check the purchase receipt in EDD, EDD lists the correct IP address (which does in fact match the country the customer selected).

So the problem I'm having is that it looks like PayPal's IP address is being sent to Taxamo instead of the actual customer's IP address. This results in every single transaction having conflicting evidence, so it doesn't actually log in Taxamo correctly at all.

**Comment by rhyswynne** [comment]
Hi @nosegraze,

Could you try the latest commit? https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/commit/e5846dd2a3df873086f0970284c692f5d27d8c54 - that should fix it.

If not, please let me know.

**Comment by nosegraze** [comment]
I'll try that and get back to you. Thanks very much!

**Comment by nosegraze** [comment]
I can confirm that the correct IP is now being sent to Taxamo. Thanks again!
