### ISSUE TITLE
Billing address required when cart total = 0.00

### ISSUE THREAD

**Issue by jakemcmurchie** [rhyswynne/easy-digital-downloads-taxamo-integration#30]
If the cart total *after* discount codes applied is zero, the billing address fields aren't displayed, but a "Please confirm that the billing address is correct." error is displayed when "purchase" is clicked.

More...
taxamo-edd-integration.php line 421
check_self_declaration() is set to return if edd_get_cart_subtotal() == 0
But edd_get_cart_subtotal() "Gets the total price amount in the cart before taxes and before any discounts"

**Comment by rhyswynne** [comment]
I can replicate :)

Right not sure when I will be able to look at it, but so I remember.

If you buy a free product, this error #20 is fixed, so doesn't occur then.

HOWEVER if you buy a paid product and get a 100% discount, this error does occur.

Occurs if billing address is not in IP range.

**Comment by jakemcmurchie** [comment]
Thanks Rhys.
If it helps [anyone else], I've changed line 421
            if ( edd_get_cart_subtotal() == 0 ) {
to
            if ( edd_get_cart_total() == 0 ) {

**Comment by rhyswynne** [comment]
Hi @jakemcmurchie,

Could you have a look at https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/commit/d61341d679cbee71241961ceeaca7963e31de849 please? It's 1.4.1-beta and potentially fixes it.

**Comment by jakemcmurchie** [comment]
Thank you Rhys. Yes, that's the fix I implemented and so far seems to work for my use case. I'll investigate further when I have a little time in the next few days. I'm currently unable to test in countries outside the UK (where a different tax rate will apply).

**Comment by rhyswynne** [comment]
Going to close this, as I think if something was broken because of it it'd turn up by now.

**Comment by rhyswynne** [comment]
If not feel free to reopen :)

**Comment by jakemcmurchie** [comment]
Seems to be working well to me. Thanks Rhys.
