### ISSUE TITLE
v1.5 Brings Back The #28 Bug

### ISSUE THREAD

**Issue by maurisrx** [rhyswynne/easy-digital-downloads-taxamo-integration#31]
Hello,

I've just updated the plugin to v1.5 and encountered an old bug #28 is back again in the plugin. Is v1.5 a critical update so I can skip it and stick with v1.4?

The v1.5 bug image: http://screencast.com/t/pheHcN53af1

Thanks,
Mauris

**Comment by rhyswynne** [comment]
Hi Mauris,

Gah! I thought I tested for it :(.

It's not a critical update. It's only a critical update if you want prices including tax. If you want it excluding tax, then you don't need to update.

I thought I got it. I will look at it over the weekend and prepare a fix.

**Comment by maurisrx** [comment]
Thank you Ryhs for the answer. I will downgrade to v1.4 for the moment to get it worked again

**Comment by rhyswynne** [comment]
No problem. Sorry about this - I thought I got it :(

**Comment by maurisrx** [comment]
Never mind, v1.4 works fine for me though. Thanks for the effort on the plugin.

**Comment by rhyswynne** [comment]
Does 1.5 still work okay if checkout excludes tax? I can only seem to see the above if checkout includes tax.

**Comment by rhyswynne** [comment]
Have a look at https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/commit/6692651d8c7896e3059bbeeb37821b39dafaa69f, this may fix this issue.

**Comment by maurisrx** [comment]
Thanks, it seems it has fixed the bug: http://screencast.com/t/ESu7ELNE6W

**Comment by rhyswynne** [comment]
Superb! Going to close this.
