### ISSUE TITLE
v1.6: Excluding Tax Price Bug

### ISSUE THREAD

**Issue by maurisrx** [rhyswynne/easy-digital-downloads-taxamo-integration#33]
Hello,

I use the plugin v1.6. I found a bug when checking out. Even though I set the "price entered with tax" setting to be "exclusive of tax", the price on the checkout use the price set as "inclusive of tax". Please check the image below.

http://screencast.com/t/6e6XO99e9b

I tried to checkout from Netherlands using VPN. I set the price to $10. I also set the price to be exclusive of tax. But the total amount indicates the price is set to inclusive of tax. So I had to downgrade to v1.4 to make it works again.

Thanks,
Mauris

**Comment by rhyswynne** [comment]
Hi Mauris,

Odd, I'm unable to replicate this. Have you a live version I can view? Also could you tell me what plugins you are using.

Rhys

**Comment by maurisrx** [comment]
Hi Rhys,

The live site is using v1.4 to eliminate the issue. I am trying to upload it to staging URL so you can see it. Here are my active plugins:

-- WordPress Active Plugins

Adminer: 1.4.2
AffiliateWP: 1.6.5
AffiliateWP - Affiliate Forms For Ninja Forms: 1.0.1
AffiliateWP - Order Details For Affiliates: 1.0.1
AffiliateWP - PayPal Payouts: 1.1
AffiliateWP - Recurring Referrals: 1.4.2
Auto Affiliate Links: 5.0.2
bbPress: 2.5.8
bbPress - Private Replies: 1.3.2
bbPress Genesis Extend: 1.1.1
Buddy-bbPress Support Topic: 2.0
Compress PNG for WP: 1.3.5
Default featured image: 1.4
Disable WP Registration Page: 1.0.1
Disable WP Toolbar: 0.1
Duplicator: 0.5.24
Easy Digital Downloads: 2.4.2
Easy Digital Downloads - Auto Register - Custom: 1.2.1
Easy Digital Downloads - Recount Earnings: 1.0.2
Easy Digital Downloads - Sales Number: 1.0
Easy Digital Downloads - Slug & Labels Modifier: 1.0
Easy Digital Downloads - Software Licenses: 3.2.6
Easy Digital Downloads - Taxamo Integration 1.6
Easy Digital Downloads Free Link: 1.0.3.1
Easy Login Redirect: 0.1
Easy Post Series: 1.1.1
EDD Changelog: 1.1
EDD Mailchimp Subscribe: 1.1.1
Genesis Connect for Easy Digital Downloads: 1.3.0
Google Analytics by Yoast: 5.4.5
Jetpack by WordPress.com: 3.6.1
Link Manager: 0.1-beta
List Custom Taxonomy Widget: 3.3
Ninja Forms: 2.9.24
Ninja Forms MailChimp Opt-ins: 1.1.0
oEmbed Gist: 1.8.0
Pretty Link Lite: 1.6.8
Simple Login Log: 1.1.0
Tabby Responsive Tabs: 1.2.1
WP125 - Custom: 1.5.3
WP Lightbox 2: 3.0.4
Wp Mail Bank: 1.25
WP Spam Fighter: 0.5.1
WYSIWYG Inline Code Command: 2.0
YM Affiliate URLs: 0.1
YM bbPress Feature Topic: 0.1
YM Custom bbPress Modification: 0.1
YM Custom bbPress Votes: 0.1
YM Docs: 1.0
Yoast SEO: 2.3.2

Thanks,
Mauris

**Comment by maurisrx** [comment]
Hi Ryhs,

Here is the staging URL: http://www.yudhistiramauris.com/products/simple-drop-cap-pro/.

You can try to add the product to cart and then checkout. You can see the issue if you access it from EU area that is charged for EU VAT.

Thanks,
Mauris

**Comment by rhyswynne** [comment]
Sorry Mauris.

Sorry I missed this.

Can I have a login please? Email me at rhys at winwar dot co dot uk if you don't want to share it.

Thanks

**Comment by maurisrx** [comment]
I've sent an admin account details to your email. Let me know if you need anything else.

Mauris

**Comment by rhyswynne** [comment]
Hi Marius,

Can you resend them? I didn't receive anything.

Rhys

**Comment by maurisrx** [comment]
I've resent it. Let me know if you need anything else.

Mauris
