### ISSUE TITLE
Lie about my country

### ISSUE THREAD

**Issue by samikeijonen** [rhyswynne/easy-digital-downloads-taxamo-integration#5]
If I lie my country at the checkout, I can still purchase without any errors but that won't be recorded in Taxamo. Should it be this way?

**Comment by rhyswynne** [comment]
Right we have an update from Taxamo. Turns out we'd have to self declare as a last resort. So will integrate this (see #6)

**Comment by rhyswynne** [comment]
Hi @samikeijonen. The latest commit (fb36a1e) should prevent solve this issue (give #6 a read too), if happy, will close.

**Comment by samikeijonen** [comment]
I did  a quick test and I can see the toggled checkbox when I lie about my country.

**Comment by rhyswynne** [comment]
Going to close this. As I think #6 should've fixed it.
