### ISSUE TITLE
Self Declaration Required

### ISSUE THREAD

**Issue by rhyswynne** [rhyswynne/easy-digital-downloads-taxamo-integration#6]
From Taxamo:-

"The plugin should have notified me of conflicting evidence and prompted for Self Declaration of location but it did not."

This means that if the IP address isn't located in the same place as the billing address, then there needs to be a notification to confirm this (like what Woocommerce has done with theirs -  http://docs.woothemes.com/document/woocommerce-taxamo/)

This is pretty much a blocker, so will get onto it this weekend, but if anybody fancies helping, feel free :)

**Comment by pippinsplugins** [comment]
Does the Taxamo API return the country the IP is detected to be from?

**Comment by rhyswynne** [comment]
Yes, but I had to write a wrapper function, but it does the job - https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/master/includes/functions.php#L10

Thinking out loud, this is the methodology we need:-

1. First and foremost, every tax calculation should be done via the billing address.
2. If the billing address isn't present, then we should revert back to the IP address.
3. If the IP address' country doesn't match the billing address, then we should force a checkbox to appear saying "I swear I'm from [Billing Address]" (or more legally correct text).
4. We hide the checkbox should there be
5. There is a "Force Tax Country" setting, which allows you to force the country's tax to be adopted, no matter what else appears. Should the tickbox be clicked, we set this value to the billing address country.
6. User cannot check out if this isn't checked (though if the IP matches billing country, they can).

The only small problem I can see (which isn't really one), is that if somebody's IP is different from billing address, then it could affect transactions (so if you're in the UK, but your billing address is in the US, then you will appear to pay 20% tax on the checkout screen, but when it's sent to Paypal then it'll be 0% tax). I think it's an edge case in most cases. Of course, I'm sure if I sit down to learn Ajax and updating the cart in real time, it should be easy to fix this :).

That's the roadmap I wish to take. I'll get cracking on it this weekend.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by rhyswynne** [comment]
@pippinsplugins could you give #fb36a1e commit a test? Think i've cracked this, but would like a second opinion :)

**Comment by pippinsplugins** [comment]
Sorry for being slow.

Looks great to me.

I just approved the request on WordPress.org/

**Comment by rhyswynne** [comment]
No worries Pippin, understand you're taking time out to do this.

Thanks for testing. Will close this issue.
