### ISSUE TITLE
i18n/general code cleanup

### ISSUE THREAD

**Issue by rhyswynne** [rhyswynne/easy-digital-downloads-taxamo-integration#8]
Now this is launched I'm sticking things I want fixing in here, which may have been missed.

The first thing is i18n. Obviously with a plugin like this probably is going to be used all over Europe, so want this to be on point. Problem was this was kind of rushed to get this ready for Jan 1st, and I probably use about 20 different text domains through the code.

Secondly I'd like to do a clean up the code. It's okay, but probably could do some work. Make sure everything's commented mainly.

**Comment by samikeijonen** [comment]
I can help with all the i18n related if you need help. And translate in Finnish.

**Comment by rhyswynne** [comment]
Thanks @samikeijonen! I will work on this tomorrow/this weekend, to try and clean up the code. Would be interested in a Finnish translation (even if it's just a partial one, that's cool!)

**Comment by samikeijonen** [comment]
Also you can remove EDD updater related stuff. If you don't mind I'll check the code more closely over the weekend.

**Comment by rhyswynne** [comment]
It's upto you but it would be appreciated :)
