### ISSUE TITLE
Loading taxamo.all.js

### ISSUE THREAD

**Issue by samikeijonen** [rhyswynne/easy-digital-downloads-taxamo-integration#9]
Is `taxamo.all.js` needed anywhere else but in checkout page? If not I suggest that we load it only in checkout page. There is `edd_is_checkout()` function for it.

**Comment by samikeijonen** [comment]
Same goes for `scripts.js` file.

**Comment by rhyswynne** [comment]
`taxamo.all.js` shouldn't be loaded, at least at the version currently on the github. It's commented out (or should be!) - https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/master/includes/scripts.php#L19 - so we can remove that line.

Scripts doesn't need to be loaded in. It can be wrapped in `edd_is_checkout()` safely. :)

**Comment by samikeijonen** [comment]
`taxamo.all.js` it's loaded from here.

https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/d8bd69d0aabd889a81390245feb65056c92340bf/includes/libraries/taxamo-api/enqueue-js.php

**Comment by rhyswynne** [comment]
Oh so it is.

Yeah probably needs removing!

**Comment by rhyswynne** [comment]
Okay, that I have a funny feeling that file probably shouldn't be pulled in. I'll look at it it with #8.

**Comment by rhyswynne** [comment]
Yep. Shouldn't be in. Removed
